### ISSUE TITLE
Header image does not scale on older mobile devices

### ISSUE THREAD

**Issue by tomasholderness** [RichardLitt/stranded-by-trump#12]
Expected behavior: header image scales to fit device, first heading/paragraph immediately visible below title and buttons.

Actual behavior: header image not scaled, user must scroll one whole screen to get to content.

Bug confirmed on following devices:
- iPhone 5s, iOS 7.1, Safari 7 (Browserstack, physical device)
- iPhone 5s, iOS 7.1, Chrome 47 (Browserstack, physical device)

<img width="274" alt="screen shot 2017-01-28 at 11 03 13 pm" src="https://cloud.githubusercontent.com/assets/944642/22401770/8c3d1310-e5ae-11e6-8931-3fdf9d07bdeb.png">
<img width="262" alt="screen shot 2017-01-28 at 11 03 20 pm" src="https://cloud.githubusercontent.com/assets/944642/22401772/9c5dc37a-e5ae-11e6-83ae-d4248fef7c86.png">
<img width="274" alt="screen shot 2017-01-28 at 11 03 31 pm" src="https://cloud.githubusercontent.com/assets/944642/22401773/9e225284-e5ae-11e6-9f80-ba6cbc919742.png">

**Comment by tomasholderness** [comment]
This is due to site-header using "vh" units;

```css
.site-header {
    width: 100%;
    height: 80vh;
    min-height: 400px;
    background-image: url(/assets/img/protest.jpg);
    background-size: cover;
    background-position: center;
}```

Support in Safari was buggy until version 8: http://caniuse.com/#feat=viewport-units

**Comment by tomasholderness** [comment]
Here's a potential fix in SCSS (as provided by caniuse.com (see previous comment) but I don't have enough Jekyll/SCSS experience to verify if it would work.

https://gist.github.com/BenMorel/e9e34c08360ebbbd0634

**Comment by jvivs** [comment]
@talltom Applied that fix in #21 but don't have a device w/ an old enough version to test. Checked out in a few browsers and simulator w/ iPhone5s and iOS10 and it didn't break anything.

**Comment by RichardLitt** [comment]
@talltom Should be merged. Can you check on older devices?

**Comment by tomasholderness** [comment]
Looks great @jvivs @RichardLitt , working on both Safari and Chrome on iOS 7.1 

<img width="256" alt="screen shot 2017-01-29 at 12 51 05 pm" src="https://cloud.githubusercontent.com/assets/944642/22406484/e0915b60-e621-11e6-819f-712274e5c357.png">
