### ISSUE TITLE
About Page Copy

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/stranded-by-trump#14]
Stranded By Trump was made by a group of friends in Buenos Aires who felt dispirited and dejected by the news coming out of the U.S. Rather than sit around and feel powerless, we decided to build a site to help, however we could - some friends on Twitter helped out, too. We are nominally non-partisan, but we acknowledge that Trump's executive orders were racist, xenophobic, alienating, and decidedly un-American. We believe that no one person is illegal, and that America is at its best when it is welcoming. 

If you'd like to help out, please contact us at [strandedbytrump@gmail.com](mailto:strandedbytrump@gmail.com).

**Comment by KevinColemanInc** [comment]
finished
