### ISSUE TITLE
If Header Image Load Fails "I'm Stranded" Button Not Visible

### ISSUE THREAD

**Issue by tomasholderness** [RichardLitt/stranded-by-trump#15]
On really old devices (listed below) the header image does not load. The white background therefore masks the "I'm stranded button".

To allow graceful failure the button color should be changed to something which shows up on white. As I don't have access to physical devices this old I can't debug properly to see why the header image won't load.

- iOS 3, Safari 4 (emulator)
- Android 1.6, in-built Android browser (emulator)

Possibly related to #12 

<img width="351" alt="screen shot 2017-01-28 at 11 22 21 pm" src="https://cloud.githubusercontent.com/assets/944642/22401837/6c793eac-e5b1-11e6-9e36-c960c18f33d7.png">

**Comment by tomasholderness** [comment]
Fixed in 76ad7d78b02c6b920cd1c213af19d5e920e728d7

**Comment by RichardLitt** [comment]
Thank you!
