### ISSUE TITLE
add donate to ACLU link

### ISSUE THREAD

**Issue by KevinColemanInc** [RichardLitt/stranded-by-trump#2]
https://action.aclu.org/secure/he-discriminated-we-sued?s_src=UNV170101INA&ms=web_hero_Inaug_FOIA

**Comment by RichardLitt** [comment]
Also add National Immigration Center

**Comment by RichardLitt** [comment]
Can you get me good links for these?

**Comment by RichardLitt** [comment]
the National Immigration Law Center, the International Refugee Assistance Project

**Comment by RichardLitt** [comment]
National Immigration Law Center: https://nilc.z2systems.com/np/clients/nilc/donation.jsp?campaign=15&

International refugee assistance project: https://irap.urbanjustice.org/civicrm/contribute/transact?reset=1&id=13
