### ISSUE TITLE
Add list of languages spoken in banned countries

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/stranded-by-trump#26]
We need translators, but Arabic and Parsi are _not_ the only languages! Can someone help me source a list of possible major languages spoken in the banned countries?

**Comment by RichardLitt** [comment]
Somalia: English, Italian, Somali, Standard Arabic
Iraq: Turkmen, Standard Arabic
Iran: Parsi

**Comment by yelkhatib** [comment]
Iraq: **Arabic** (Iraqi dialect), **Kurdish** (many variants e.g. Sorani, Kurmanji), English
Iran: **Farsi**, Balochi, Azerbaijani, Arabic (similar to Iraqi dialect)
Libya: **Arabic** (Libyan dialect), Berber
Somalia: **Somali**, Arabic (Somali dialect), Zigua, English, Italian
Sudan: **Arabic** (Sudanese dialect), English, Italian
Syria: **Arabic** (evantine dialect), **Kurmanji**, Armenian, French, English
Yemen: **Arabic** (Yemeni dialect and some South Arabian variants like Mehri and Soqotri), English

added **bold** for majority languages

**Comment by RichardLitt** [comment]
Ha! Thank you, @yelkhatib. Awesome. Kurdish! Of course. 

Ok. Let's add this to the site, and hopefully get i18n running.

**Comment by yelkhatib** [comment]
note: Modern Standard Arabic is the written language in all these countries (but Iran) and is sort of the lingua franca for spoken language but not for less educated folks

**Comment by RichardLitt** [comment]
Yep. Dialects would be great! Added to the website; what do you think? 

```
# Contribute

We need help! Currently, there are a few things you can do to help @StrandedByTrump have more impact:
- **Share on Social Media**;
- **Translate**: We need translations in Arabic, Kurdish, Farsi, Balochi, Azerbaijani, Berber, Somali, Zigua, Italian, Kurmanji, Armenian, and French. If you speak any of these, get in touch. For Arabic, if you speak a regional dialect or can translate, also get in touch.
- **Help source data**: We're working on two things: a list of US Representatives stances on the Ban, and a list of resources for who is in the airports right now. Tweet at us or email!
- **Code**: We need to get i18n running for the translators. Can you help? Also, look at [the issues here](https://github.com/RichardLitt/stranded-by-trump).
```

**Comment by yelkhatib** [comment]
looks great, thank you for a great intiative. i added bold for the main languages that the majority of people speak in each country. (e.g. Zigua is a minority language AFAIK)

**Comment by RichardLitt** [comment]
Thank you!

**Comment by RichardLitt** [comment]
Alright. This is here, which is a good start. Closing this issue for now; hope we get some contacts.
