### ISSUE TITLE
Copy

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/stranded-by-trump#4]
# Stranded By Trump

Help refugees and travellers in need, today. #NoMuslimBan #NoBanNoWall #Resist

## About

Late on Friday, President Trump issued an executive order banning entry to the United States for citizens from Iraq, Iran, Libya, Somalia, Sudan, Yemen, and Syria.

## For Travelers

What to know if you are denied entry to the Unites States

- Know your rights!

  - ACLU

  - Don't Sign

- Reach out for housing

  https://twitter.com/bchesky/status/825517729251684352

- Join FACEBOOK GROUP to find housing

## For Helpers

- Offer housing!

https://twitter.com/bchesky/status/825517729251684352

- Protest

  - Link to protests

- Donate!

  - We would like to do this; if you know how legally, get in touch

**Comment by KevinColemanInc** [comment]
done
